import pandas as pd
population=pd.read_excel("population.xls").iloc[2:,:]
gdp=pd.read_excel("GDP.xls").iloc[2:,:]
income=pd.read_excel("income.xls").iloc[2:,:]
population.set_index("数据库：分省年度数据",inplace=True)
gdp.set_index("数据库：分省年度数据",inplace=True)
income.set_index("数据库：分省年度数据",inplace=True)
population.columns=population.loc['地区',:]
population.drop(["地区"],inplace=True)
gdp.columns=gdp.loc['地区',:]
gdp.drop(["地区"],inplace=True)
income.columns=income.loc['地区',:]
income.drop(["地区"],inplace=True)
import pandas as pd
qinghai_gdp=pd.read_excel("qinghai.xls",sheet_name="GDP")
qinghai_income=pd.read_excel("qinghai.xls",sheet_name="income")
qinghai_population=pd.read_excel("qinghai.xls",sheet_name="population")
qinghai_gdp.set_index("数据库：青海年度数据",inplace=True)
qinghai_gdp.columns=qinghai_gdp.loc["地区",:]
qinghai_population.set_index("数据库：分省年度数据",inplace=True)
qinghai_population.columns=qinghai_population.loc["地区",:]
qinghai_income.set_index("数据库：分省年度数据",inplace=True)
qinghai_income.columns=qinghai_income.loc["地区",:]
population=pd.concat([population,qinghai_population],axis=0)
population.dropna(inplace=True)
gdp=pd.concat([gdp,qinghai_gdp],axis=0)
gdp.dropna(inplace=True)
income=pd.concat([income,qinghai_income],axis=0)
income.dropna(inplace=True)
gdp3=gdp.drop_duplicates(inplace=False)
income.drop_duplicates(inplace=True)
population.drop_duplicates(inplace=True)
gdp.drop(index="地区",inplace=True)
income.drop(index="地区",inplace=True)
population.drop(index="地区",inplace=True)
print(gdp[gdp.duplicated()==True])
gdp.drop_duplicates(inplace=True)
col_mean=income.mean(axis=0)
print(col_mean)
mean_gdp=(gdp*100000000)/(population*10000)
print(mean_gdp.head(10))
gdp_2021=gdp.loc[:,"2021年"]
poputation_2021=population.loc[:,"2021年"]
income_2021=income.loc[:,"2021年"]
info_2021=pd.concat([gdp_2021,income_2021,poputation_2021],axis=1)
info_2021.columns=['GDP','人均收入','人口总数']
info_2021
import matplotlib.pyplot as plt 
population1=population.drop("区域",axis=1)
x_axis_data=population1.columns
beijing_y_axis_data=population1.loc['北京市',:]
tianjing_y_axis_data=population1.loc["天津市",:]
shanghai_y_axis_data=population1.loc["上海市",:]
chongqing_y_axis_data=population1.loc["重庆市",:]
plt.rcParams['font.family']=['SimHei']
plt.plot(x_axis_data,beijing_y_axis_data,label="北京市")
plt.plot(x_axis_data,tianjing_y_axis_data,label="天津市")
plt.plot(x_axis_data,shanghai_y_axis_data,label="上海市")
plt.plot(x_axis_data,chongqing_y_axis_data,label="重庆")
plt.legend(['北京市',"天津市","上海市","重庆市"])
plt.ylabel("人口数量")
plt.xlabel("年份")
plt.title('直辖市人口数量图')
plt.rcParams["font.sans-serif"]=['SimHei']
info_2021.sort_values("人均收入",inplace=True)
x_axis_data1=np.array(info_2021.iloc[:10,1])
y_axis_data1=np.array(info_2021.index[:10])
x_axis_data2=np.array(info_2021.iloc[-10:,1])
y_axis_data2=np.array(info_2021.index[-10:])
plt.figure(figsize=(10,7))
plt.subplot(2,2,1)
plt.barh(y_axis_data1,x_axis_data1)
plt.title("人均收入后十名")
plt.show()
plt.subplot(1,1,1)
plt.barh(y_axis_data2,x_axis_data2)
plt.title("人均收入前十名")
gdp1=gdp.drop("区域",axis=1,inplace=False).T
gdp1.sort_values("北京市",inplace=True)
gdp2=gdp1.apply(lambda x :x.sum(),axis=1)
y=gdp2.pct_change()
x=gdp2.pct_change().index
plt.figure(figsize=(10,7))
plt.title("2012年-2021年增长情况")
plt.bar(x,y)
plt.show()
plt.title("2021年GDP后五个省")

info_2021.sort_values("GDP").iloc[:5,0].plot.pie(autopct='%.2f%%')
plt.show()
plt.title("2021年GDP前五个省")

info_2021.sort_values("GDP").iloc[-5:,0].plot.pie(autopct='%.2f%%')
plt.show()